/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { AddPetMutationRequest, AddPetMutationResponse, AddPet400, AddPet422 } from "./src/pets/model/AddPet.ts";
import type { CreateUserMutationRequest, CreateUserMutationResponse } from "./src/pets/model/CreateUser.ts";
import type { CreateUsersWithListInputMutationRequest, CreateUsersWithListInputMutationResponse } from "./src/pets/model/CreateUsersWithListInput.ts";
import type { DeleteOrderMutationResponse, DeleteOrderPathParams, DeleteOrder400, DeleteOrder404 } from "./src/pets/model/DeleteOrder.ts";
import type { DeletePetMutationResponse, DeletePetPathParams, DeletePetHeaderParams, DeletePet400 } from "./src/pets/model/DeletePet.ts";
import type { DeleteUserMutationResponse, DeleteUserPathParams, DeleteUser400, DeleteUser404 } from "./src/pets/model/DeleteUser.ts";
import type { FindPetsByStatusQueryResponse, FindPetsByStatusQueryParams, FindPetsByStatus400 } from "./src/pets/model/FindPetsByStatus.ts";
import type { FindPetsByTagsQueryResponse, FindPetsByTagsQueryParams, FindPetsByTags400 } from "./src/pets/model/FindPetsByTags.ts";
import type { GetInventoryQueryResponse } from "./src/pets/model/GetInventory.ts";
import type { GetOrderByIdQueryResponse, GetOrderByIdPathParams, GetOrderById400, GetOrderById404 } from "./src/pets/model/GetOrderById.ts";
import type { GetPetByIdQueryResponse, GetPetByIdPathParams, GetPetById400, GetPetById404 } from "./src/pets/model/GetPetById.ts";
import type { GetUserByNameQueryResponse, GetUserByNamePathParams, GetUserByName400, GetUserByName404 } from "./src/pets/model/GetUserByName.ts";
import type { LoginUserQueryResponse, LoginUserQueryParams, LoginUser400 } from "./src/pets/model/LoginUser.ts";
import type { LogoutUserQueryResponse } from "./src/pets/model/LogoutUser.ts";
import type { PlaceOrderMutationRequest, PlaceOrderMutationResponse, PlaceOrder400, PlaceOrder422 } from "./src/pets/model/PlaceOrder.ts";
import type { UpdatePetMutationRequest, UpdatePetMutationResponse, UpdatePet400, UpdatePet404, UpdatePet422 } from "./src/pets/model/UpdatePet.ts";
import type { UpdatePetWithFormMutationResponse, UpdatePetWithFormPathParams, UpdatePetWithFormQueryParams, UpdatePetWithForm400 } from "./src/pets/model/UpdatePetWithForm.ts";
import type { UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams, UpdateUser400, UpdateUser404 } from "./src/pets/model/UpdateUser.ts";
import type { UploadFileMutationRequest, UploadFileMutationResponse, UploadFilePathParams, UploadFileQueryParams, UploadFile400, UploadFile404 } from "./src/pets/model/UploadFile.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getUpdatePetUrl() {
  const res = { method: 'PUT', url: `https://api.pets.local/pet` as const }  
  return res
}

/**
 * @description Update an existing pet by Id.
 * @summary Update an existing pet.
 * {@link /pet}
 */
export async function updatePet({ data }: { data: UpdatePetMutationRequest }, config: Partial<RequestConfig<UpdatePetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePetMutationResponse, ResponseErrorConfig<UpdatePet400 | UpdatePet404 | UpdatePet422>, UpdatePetMutationRequest>({ method : "PUT", url : getUpdatePetUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getAddPetUrl() {
  const res = { method: 'POST', url: `https://api.pets.local/pet` as const }  
  return res
}

/**
 * @description Add a new pet to the store.
 * @summary Add a new pet to the store.
 * {@link /pet}
 */
export async function addPet({ data }: { data: AddPetMutationRequest }, config: Partial<RequestConfig<AddPetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AddPetMutationResponse, ResponseErrorConfig<AddPet400 | AddPet422>, AddPetMutationRequest>({ method : "POST", url : getAddPetUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getFindPetsByStatusUrl() {
  const res = { method: 'GET', url: `https://api.pets.local/pet/findByStatus` as const }  
  return res
}

/**
 * @description Multiple status values can be provided with comma separated strings.
 * @summary Finds Pets by status.
 * {@link /pet/findByStatus}
 */
export async function findPetsByStatus({ params }: { params: FindPetsByStatusQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<FindPetsByStatusQueryResponse, ResponseErrorConfig<FindPetsByStatus400>, unknown>({ method : "GET", url : getFindPetsByStatusUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getFindPetsByTagsUrl() {
  const res = { method: 'GET', url: `https://api.pets.local/pet/findByTags` as const }  
  return res
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags.
 * {@link /pet/findByTags}
 */
export async function findPetsByTags({ params }: { params: FindPetsByTagsQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>, unknown>({ method : "GET", url : getFindPetsByTagsUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getGetPetByIdUrl({ petId }: { petId: GetPetByIdPathParams["petId"] }) {
  const res = { method: 'GET', url: `https://api.pets.local/pet/${petId}` as const }  
  return res
}

/**
 * @description Returns a single pet.
 * @summary Find pet by ID.
 * {@link /pet/:petId}
 */
export async function getPetById({ petId }: { petId: GetPetByIdPathParams["petId"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPetByIdQueryResponse, ResponseErrorConfig<GetPetById400 | GetPetById404>, unknown>({ method : "GET", url : getGetPetByIdUrl({ petId }).url.toString(), ... requestConfig })  
  return res.data
}

function getUpdatePetWithFormUrl({ petId }: { petId: UpdatePetWithFormPathParams["petId"] }) {
  const res = { method: 'POST', url: `https://api.pets.local/pet/${petId}` as const }  
  return res
}

/**
 * @description Updates a pet resource based on the form data.
 * @summary Updates a pet in the store with form data.
 * {@link /pet/:petId}
 */
export async function updatePetWithForm({ petId, params }: { petId: UpdatePetWithFormPathParams["petId"]; params?: UpdatePetWithFormQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UpdatePetWithFormMutationResponse, ResponseErrorConfig<UpdatePetWithForm400>, unknown>({ method : "POST", url : getUpdatePetWithFormUrl({ petId }).url.toString(), params, ... requestConfig })  
  return res.data
}

function getDeletePetUrl({ petId }: { petId: DeletePetPathParams["petId"] }) {
  const res = { method: 'DELETE', url: `https://api.pets.local/pet/${petId}` as const }  
  return res
}

/**
 * @description Delete a pet.
 * @summary Deletes a pet.
 * {@link /pet/:petId}
 */
export async function deletePet({ petId, headers }: { petId: DeletePetPathParams["petId"]; headers?: DeletePetHeaderParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeletePetMutationResponse, ResponseErrorConfig<DeletePet400>, unknown>({ method : "DELETE", url : getDeletePetUrl({ petId }).url.toString(), ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

function getUploadFileUrl({ petId }: { petId: UploadFilePathParams["petId"] }) {
  const res = { method: 'POST', url: `https://api.pets.local/pet/${petId}/uploadImage` as const }  
  return res
}

/**
 * @description Upload image of the pet.
 * @summary Uploads an image.
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile({ petId, data, params }: { petId: UploadFilePathParams["petId"]; data?: UploadFileMutationRequest; params?: UploadFileQueryParams }, config: Partial<RequestConfig<UploadFileMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UploadFileMutationResponse, ResponseErrorConfig<UploadFile400 | UploadFile404>, UploadFileMutationRequest>({ method : "POST", url : getUploadFileUrl({ petId }).url.toString(), params, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/octet-stream', ...requestConfig.headers } })  
  return res.data
}

function getGetInventoryUrl() {
  const res = { method: 'GET', url: `https://api.pets.local/store/inventory` as const }  
  return res
}

/**
 * @description Returns a map of status codes to quantities.
 * @summary Returns pet inventories by status.
 * {@link /store/inventory}
 */
export async function getInventory(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInventoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetInventoryUrl().url.toString(), ... requestConfig })  
  return res.data
}

function getPlaceOrderUrl() {
  const res = { method: 'POST', url: `https://api.pets.local/store/order` as const }  
  return res
}

/**
 * @description Place a new order in the store.
 * @summary Place an order for a pet.
 * {@link /store/order}
 */
export async function placeOrder({ data }: { data?: PlaceOrderMutationRequest }, config: Partial<RequestConfig<PlaceOrderMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PlaceOrderMutationResponse, ResponseErrorConfig<PlaceOrder400 | PlaceOrder422>, PlaceOrderMutationRequest>({ method : "POST", url : getPlaceOrderUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getGetOrderByIdUrl({ orderId }: { orderId: GetOrderByIdPathParams["orderId"] }) {
  const res = { method: 'GET', url: `https://api.pets.local/store/order/${orderId}` as const }  
  return res
}

/**
 * @description For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID.
 * {@link /store/order/:orderId}
 */
export async function getOrderById({ orderId }: { orderId: GetOrderByIdPathParams["orderId"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrderByIdQueryResponse, ResponseErrorConfig<GetOrderById400 | GetOrderById404>, unknown>({ method : "GET", url : getGetOrderByIdUrl({ orderId }).url.toString(), ... requestConfig })  
  return res.data
}

function getDeleteOrderUrl({ orderId }: { orderId: DeleteOrderPathParams["orderId"] }) {
  const res = { method: 'DELETE', url: `https://api.pets.local/store/order/${orderId}` as const }  
  return res
}

/**
 * @description For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
 * @summary Delete purchase order by identifier.
 * {@link /store/order/:orderId}
 */
export async function deleteOrder({ orderId }: { orderId: DeleteOrderPathParams["orderId"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteOrderMutationResponse, ResponseErrorConfig<DeleteOrder400 | DeleteOrder404>, unknown>({ method : "DELETE", url : getDeleteOrderUrl({ orderId }).url.toString(), ... requestConfig })  
  return res.data
}

function getCreateUserUrl() {
  const res = { method: 'POST', url: `https://api.pets.local/user` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Create user.
 * {@link /user}
 */
export async function createUser({ data }: { data?: CreateUserMutationRequest }, config: Partial<RequestConfig<CreateUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateUserMutationResponse, ResponseErrorConfig<Error>, CreateUserMutationRequest>({ method : "POST", url : getCreateUserUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getCreateUsersWithListInputUrl() {
  const res = { method: 'POST', url: `https://api.pets.local/user/createWithList` as const }  
  return res
}

/**
 * @description Creates list of users with given input array.
 * @summary Creates list of users with given input array.
 * {@link /user/createWithList}
 */
export async function createUsersWithListInput({ data }: { data?: CreateUsersWithListInputMutationRequest }, config: Partial<RequestConfig<CreateUsersWithListInputMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateUsersWithListInputMutationResponse, ResponseErrorConfig<Error>, CreateUsersWithListInputMutationRequest>({ method : "POST", url : getCreateUsersWithListInputUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getLoginUserUrl() {
  const res = { method: 'GET', url: `https://api.pets.local/user/login` as const }  
  return res
}

/**
 * @description Log into the system.
 * @summary Logs user into the system.
 * {@link /user/login}
 */
export async function loginUser({ params }: { params?: LoginUserQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<LoginUserQueryResponse, ResponseErrorConfig<LoginUser400>, unknown>({ method : "GET", url : getLoginUserUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getLogoutUserUrl() {
  const res = { method: 'GET', url: `https://api.pets.local/user/logout` as const }  
  return res
}

/**
 * @description Log user out of the system.
 * @summary Logs out current logged in user session.
 * {@link /user/logout}
 */
export async function logoutUser(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<LogoutUserQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getLogoutUserUrl().url.toString(), ... requestConfig })  
  return res.data
}

function getGetUserByNameUrl({ username }: { username: GetUserByNamePathParams["username"] }) {
  const res = { method: 'GET', url: `https://api.pets.local/user/${username}` as const }  
  return res
}

/**
 * @description Get user detail based on username.
 * @summary Get user by user name.
 * {@link /user/:username}
 */
export async function getUserByName({ username }: { username: GetUserByNamePathParams["username"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetUserByNameQueryResponse, ResponseErrorConfig<GetUserByName400 | GetUserByName404>, unknown>({ method : "GET", url : getGetUserByNameUrl({ username }).url.toString(), ... requestConfig })  
  return res.data
}

function getUpdateUserUrl({ username }: { username: UpdateUserPathParams["username"] }) {
  const res = { method: 'PUT', url: `https://api.pets.local/user/${username}` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Update user resource.
 * {@link /user/:username}
 */
export async function updateUser({ username, data }: { username: UpdateUserPathParams["username"]; data?: UpdateUserMutationRequest }, config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404>, UpdateUserMutationRequest>({ method : "PUT", url : getUpdateUserUrl({ username }).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getDeleteUserUrl({ username }: { username: DeleteUserPathParams["username"] }) {
  const res = { method: 'DELETE', url: `https://api.pets.local/user/${username}` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Delete user resource.
 * {@link /user/:username}
 */
export async function deleteUser({ username }: { username: DeleteUserPathParams["username"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteUserMutationResponse, ResponseErrorConfig<DeleteUser400 | DeleteUser404>, unknown>({ method : "DELETE", url : getDeleteUserUrl({ username }).url.toString(), ... requestConfig })  
  return res.data
}

export const operations = {
  "updatePet": {
    "path": "/pet",
    "method": "put"
  },
  "addPet": {
    "path": "/pet",
    "method": "post"
  },
  "findPetsByStatus": {
    "path": "/pet/findByStatus",
    "method": "get"
  },
  "findPetsByTags": {
    "path": "/pet/findByTags",
    "method": "get"
  },
  "getPetById": {
    "path": "/pet/:petId",
    "method": "get"
  },
  "updatePetWithForm": {
    "path": "/pet/:petId",
    "method": "post"
  },
  "deletePet": {
    "path": "/pet/:petId",
    "method": "delete"
  },
  "uploadFile": {
    "path": "/pet/:petId/uploadImage",
    "method": "post"
  },
  "getInventory": {
    "path": "/store/inventory",
    "method": "get"
  },
  "placeOrder": {
    "path": "/store/order",
    "method": "post"
  },
  "getOrderById": {
    "path": "/store/order/:orderId",
    "method": "get"
  },
  "deleteOrder": {
    "path": "/store/order/:orderId",
    "method": "delete"
  },
  "createUser": {
    "path": "/user",
    "method": "post"
  },
  "createUsersWithListInput": {
    "path": "/user/createWithList",
    "method": "post"
  },
  "loginUser": {
    "path": "/user/login",
    "method": "get"
  },
  "logoutUser": {
    "path": "/user/logout",
    "method": "get"
  },
  "getUserByName": {
    "path": "/user/:username",
    "method": "get"
  },
  "updateUser": {
    "path": "/user/:username",
    "method": "put"
  },
  "deleteUser": {
    "path": "/user/:username",
    "method": "delete"
  }
}