/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export enum OrderStatusEnum {
    "placed" = "placed",
    "approved" = "approved",
    "delivered" = "delivered"
}

export type Order = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type integer | undefined, int64
    */
    petId?: number;
    /**
     * @type integer | undefined, int32
    */
    quantity?: number;
    /**
     * @type string | undefined, date-time
    */
    shipDate?: Date;
    /**
     * @description Order Status
     * @type string | undefined
    */
    status?: OrderStatusEnum;
    /**
     * @type boolean | undefined
    */
    complete?: boolean;
};