/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Category } from "./Category.ts";
import type { Tag } from "./Tag.ts";

export enum PetStatusEnum {
    "available" = "available",
    "pending" = "pending",
    "sold" = "sold"
}

export type Pet = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string
    */
    name: string;
    /**
     * @type object | undefined
    */
    category?: Category;
    /**
     * @type array
    */
    photoUrls: string[];
    /**
     * @type array | undefined
    */
    tags?: Tag[];
    /**
     * @description pet status in the store
     * @type string | undefined
    */
    status?: PetStatusEnum;
};